= Rust Networking 

== Some tools

- *The standard library (std::net)*: Everything need to handle tcp and udp sockets, ip address and ports
- *Tokyo*: an asynchronous runtime for writing network applications in Rust. Tokio runtime is the foundation of asynchronous applications.
- *Hyper*: an HTTP library for the Rust language.
- *Websocket* libraries: for realtime communication( ex. chat apps, or anything that needs instant updates)
- Other libraries for *databases* (used by web apps), such as Diesel, SQLx, Rusqlite. 


== Using TCP in Rust

== Using GRPC in Rust

gRPC is an open-source remote procedure call system developed by Google. 
comes with pluggable support for load balancing, authentication, tracing, etc., 
supports bidirectional streaming over HTTP/2, and provides an idiomatic implementation in 10 languages.

The Rust community has developed many gRPC implementations, notably the `tonic` and grpc `crates`. 
Both provide a full implementation of gRPC protocols.

=== tonic 

`tonic` is a fast production-ready gRPC library with async/await support out of the box. 
It focuses on flexibility and reliability. tonic has full implementation of gRPC protocols over HTTP/2. 
tonic has built-in support for compiling protocol buffer to Rustlang.
 It also supports unidirectional as well as bidirectional streaming.

=== grpc 

`grpc` is not production-ready but is worth keeping an eye on. 
The crate has a working gRPC protocol implementation and supports TLS.