= Serialization and Deserialization

Serializing means converting data structures into a format that can be stored or transmitted over the wire, while deserializing means converting data from a stored or transmitted format back into data structures. 



== Basic serialization/deserialization with Protobuf 

This example will discuss how to serialize and deserialize a simple struct using protobuf. 
Here we focus solely on the serialization/deserialization process without sending the serialized data over the wire, for instance. 

===  Protocol Buffers (Protobuf)

Protocol Buffers is a language-neutral, platform-neutral extensible mechanism for serializing structured data. 
It is widely used for inter-service communication, especially in microservices and gRPC.

=== Prost 

_prost_ is a _Protocol Buffers_ implementation for the Rust Language. 
prost generates simple, idiomatic Rust code from proto2 and proto3 files.

=== Steps to Use Protobuf in Rust 

. Install Protobuf Compiler (protoc), if it not already instaled
+
[source, bash]
----
$ sudo apt install -y protobuf-compiler  # -> Debian/Ubuntu

$ brew install protobuf                  # -> macOS (Homebrew)
----
+
. Create your project if you do not have it yet (e.g., 'basic_protobuf_example')
+
[source, bash]
----
$ cargo new basic_protobuf_example
----
+
. Add dependencies to your Cargo.toml
+
[source, toml]
----
    [dependencies]
    prost = "0.12"   # Protobuf encoding/decoding library
    prost-types = "0.12"

    [build-dependencies]
    prost-build = "0.12"  # Generates Rust code from .proto files
----
+
. Create a .proto file (message definition), for instance at 'proto/person.proto'
+
[source, bash]
----
$ mkdir proto && cd proto && touch person.proto
----
+
. Add the definition of the proto file (i.e., proto/person.proto)
+
.person.proto
[source, proto]
----
syntax = "proto3";

package person;

message Person {
  string name = 1;
  int32 age = 2;
  repeated string emails = 3;
}
----
+
. Create you `build.rs` script file at the root of your project. This script will be used by prost to generate the rust code.
+
[source, bash]
----
$ touch build.rs
----
+
. Add the content of the script
+
[source, rust]
----
fn main() {
    prost_build::compile_protos(&["proto/person.proto"], &["proto/"]).expect("Error building");
    // version for debuging the build script: 
    //let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    //println!("OUT_DIR: {:?}", out_dir);
    //if let Err(e) = prost_build::compile_protos(&["proto/person.proto"], &["proto/"]) {
    //    panic!("Failed to compile .proto files: {:?}", e);
    //}
}
----
+
. Generate Rust code from .proto
[source, bash]
+
----
$ cargo clean
----
+
. Use the generated code in a Rust program
+
[source, rust]
----
// importe the generated code
mod person {
    //This line tells Rust to include the Rust code that was generated from a .proto file by prost_build at compile time.
    include!(concat!(env!("OUT_DIR"), "/person.rs"));
}

use person::Person;  // include the struct Person from the module 'person' in the main.rs 
use prost::Message;  // required to encoding and decoding

fn main() {

    // Create a new Person instance
    let person = Person {
        name: "Alice".to_string(),
        age: 30,
        emails: vec!["alice@example.com".to_string(), "alice.work@example.com".to_string()],
    };

    println!("person instance of Person: {:?}", person);

    // Serialize data to bytes
    // Encodes the message to a buffer.
    println!("Encoding person...");
    let encoded = prost::Message::encode_to_vec(&person);
    println!("Encoded bytes: {:?}", encoded);

    // Deserialize data from bytes
    // Decodes an instance of the message from a buffer.
    println!("Decoding person...");
    let decoded = Person::decode(&*encoded).unwrap();
    println!("Decoded person: {:?}", decoded);
}
----
+
. Run your program
+
[source, bash]
----
$ cargo run 
   Compiling basic_protobof_example v0.1.0 (/Users/heversonbr/workspace/rust-dev/rust_hands_on/on_github/rust_hands_on/serialization_deserialization/basic_protobof_example)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.69s
     Running `target/debug/basic_protobof_example`

person instance of Person: Person { name: "Alice", age: 30, emails: ["alice@example.com", "alice.work@example.com"] }

Encoding person...
Encoded bytes: [10, 5, 65, 108, 105, 99, 101, 16, 30, 26, 17, 97, 108, 105, 99, 101, 64, 101, 120, 97, 109, 112, 108, 101, 46, 99, 111, 109, 26, 22, 97, 108, 105, 99, 101, 46, 119, 111, 114, 107, 64, 101, 120, 97, 109, 112, 108, 101, 46, 99, 111, 109]

Decoding person...
Decoded person: Person { name: "Alice", age: 30, emails: ["alice@example.com", "alice.work@example.com"] }
----


== References: 
- https://docs.rs/prost-build/latest/prost_build/
- https://github.com/danburkert/snazzy/tree/master
- https://github.com/tokio-rs/prost